### ISSUE TITLE
RPC is constantly behind the chain

### ISSUE THREAD

**Issue by EvgenyKhlivetsky** [anoma/namada#2979] opened 2024-04-01 11:28 UTC
My RPC is constantly behind the chain and I need to resync it from time to time.

And this is somehow related to blocks with shielded transactions. It takes half a second to process regular block and 1-1.5 minutes to process a block with a shielded transactions while `catching_up: true`, so once my rpc is synced to head and it meets a block with shielded transaction it can not run in sync with the chain, because shielded blocks slowing it up a lot. See screenshot as an example. I can share any additional details if you ask. I though it is something related to my node only and tried to figure out the problem, but it seems like it is widespread issue: [discord message](https://discord.com/channels/833618405537218590/1193958565531103272/1224267736369074219). I am running my node since height 90k if I am not mistaken, but this issue popped out since 180k block or something like that, can share any other details on demand.
<img width="973" alt="Screenshot 2024-04-01 at 14 15 51" src="https://github.com/anoma/namada/assets/69844646/266ea824-2794-49ae-8c58-1a013ea2743e">

**Comment by brentstone** [comment] 2024-04-05 07:18
We are aware of these issues, and this is a duplicate of many others related to the shielded sync speed atm. Closing.

**Closed by brentstone** 2024-04-05 07:18 UTC
