### ISSUE TITLE
Vote on Proposal Gas fee

### ISSUE THREAD

**Issue by StoneMac65** [anoma/namada#2988] opened 2024-04-03 05:34 UTC
I faced this issue trying to vote with implicit account
 ```
namadac vote-proposal     --proposal-id 497  --vote nay     --address stonese --memo "tpknam1qp5fdx37w6pr2aqep8vngzt4z5sd4qlcux8y3ht0sxfhfk7myzqvzmpvvvu" --force 
Enter your decryption password: 
Transaction added to mempool.
Wrapper transaction hash: 7B5C38FAFF9D095647A47AD7FB31FAFB4C5B6C42E8D2D09A449160306B7A28C9
Inner transaction hash: 75350E682F88606933425EB8DE75C3ACEFBAB4732631B93E84F96A5A855F872C
Wrapper transaction accepted at height 289318. Used 28 gas.
Waiting for inner transaction result...
Transaction failed.
Details: {
  "inner_tx": null,
  "info": "Error trying to apply a transaction: Gas error: Transaction gas limit exceeded",
  "log": "",
  "height": 289319,
  "hash": "75350E682F88606933425EB8DE75C3ACEFBAB4732631B93E84F96A5A855F872C",
  "code": "WasmRuntimeError",
  "gas_used": "3184"
}
```

**Comment by opsecx** [comment] 2024-04-03 09:49
Also note this is a duplicate of an issue created before yours

**Comment by StoneMac65** [comment] 2024-04-03 09:57
thanks for the heads up. I didn't notice the previous issue and also its weird how users been acting like a issue and PR police :))

**Comment by opsecx** [comment] 2024-04-03 10:32
A little weird to come off defensive on that. Would suggest closing this issue and leaving your comment in rig's so it's in one place.

**Comment by StoneMac65** [comment] 2024-04-03 10:39
> A little weird to come off defensive on that. Would suggest closing this issue and leaving your comment in rig's so it's in one place.

nah. its all good. wasn't a defensive gesture.  That's why I put the laughter at the end. anyways I hope the issue gets solved and we get to go the end of SE

**Comment by brentstone** [comment] 2024-04-06 09:09
Closing in favor of #2986

**Closed by brentstone** 2024-04-06 09:09 UTC
Labels: bug
