### ISSUE TITLE
functions like generating keypairs won't work without a genesis file

### ISSUE THREAD

**Issue by gavinly** [anoma/namada#1952] opened 2023-09-27 23:39 UTC
we want to be able to perform different functions with the binaries as stand-alones, but can't perform functions like keygen without a genesis file (and possibly other dependencies)

**Comment by gavinly** [comment] 2023-09-27 23:40
@Fraccaman

**Comment by Fraccaman** [comment] 2023-09-28 09:19
this is addressed by #1782

**Comment by sug0** [comment] 2023-09-28 09:19
Related to / duplicate of #711

**Comment by cwgoes** [comment] 2024-02-02 15:17
Should be fixed.

**Closed by cwgoes** 2024-02-02 15:17 UTC
Labels: bug, duplicate
