### ISSUE TITLE
Refactor away `BlockHeight(0)`

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#377] opened 2022-08-24 15:41 UTC
In Tendermint, the earliest possible block in a chain (i.e. genesis block) has height 1. Currently our `BlockHeight` type permits `BlockHeight(0)` which isn't a valid block height and `BlockHeight::default() == BlockHeight(0)`. The first proposed block will be at least `BlockHeight(1)`. We should avoid `BlockHeight(0)` in our code.

We could define `BlockHeight` something like:

```rust
struct BlockHeight(NonZeroU64)
```

It could be worth having different types for proposed block heights and committed block heights. e.g. `shell.storage.last_height` represents the last committed block height and so might be of type `Option<CommittedBlockHeight>`. Often when dealing with ABCI(++) logic, we are interested in the current `ProposedBlockHeight` rather than the last `CommittedBlockHeight`, so our functions could explicitly work with `ProposedBlockHeight`s only where appropriate.

**Comment by tzemanovic** [comment] 2023-10-23 09:02
duplicate of https://github.com/anoma/namada/issues/648

**Closed by tzemanovic** 2023-10-23 09:02 UTC
Labels: ledger, refactor / code quality
