### ISSUE TITLE
Gas for vote-proposal much higher for an implicit address than an established one

### ISSUE THREAD

**Issue by Rigorously** [anoma/namada#2986] opened 2024-04-02 18:43 UTC
Since the hardfork, voting with an implicit address fails without specifying a higher gas limit than the client proposes.

```
Transaction failed.
Details: {
  "inner_tx": null,
  "info": "Error trying to apply a transaction: Gas error: Transaction gas limit exceeded",
  "log": "",
  "height": 284599,
  "hash": "1837CFB501F6C86D99C1880E471F8E12FC8AE4AF58C080B310D0876ACA757D74",
  "code": "WasmRuntimeError",
  "gas_used": "3091"
}
```

After increasing the gas limit to 30000, the transaction gas fee turned out to be over 20000.

```$ namadac  vote-proposal --proposal-id 497 --address implicit --vote yay --gas-limit 30000

Enter your decryption password: 
Transaction added to mempool.
Wrapper transaction hash: 82788E5E86FB57235FAF8E895068684C9BCF3C48730B018990BD9027B8D8C0BB
Inner transaction hash: E7852AEC9C21D208E0880D6FEC784239CB684AE15C7CDBA4CEEEF7824BF9CD42
Wrapper transaction accepted at height 284602. Used 27 gas.
Waiting for inner transaction result...
Transaction was successfully applied at height 284603. Used 27543 gas.
```

Meanwhile, voting with an established account took less than 7000 gas.

```$ namadac  vote-proposal --proposal-id 497 --address established --vote yay --gas-limit 30000
Looking-up public key of tnam1qxtzqv0vxjfw4r0pf9ds2ddqg3yys924du2mjvn8 from the ledger...
Enter your decryption password: 
Transaction added to mempool.
Wrapper transaction hash: 061393E4FA4CE0DC84B9A7739EC189C9A510CDF36AD598CCD9D4C05A922741B1
Inner transaction hash: 586263CF8F654870E51656BC857ED50E2496F8A8A4D9BD601E4A8D6C9837EF87
Wrapper transaction accepted at height 284608. Used 24 gas.
Waiting for inner transaction result...
Transaction was successfully applied at height 284609. Used 6642 gas.
```

**Comment by opsecx** [comment] 2024-04-02 20:07
Got no issues here voting with implicit without specifying gas. Haven't checked how much it spends.

**Comment by opsecx** [comment] 2024-04-03 09:03
> > Got no issues here voting with implicit without specifying gas. Haven't checked how much it spends.
> 
> 
> 
> Are you voting with an implicit account instead of a validator account and how much is the gas?

I am. Not sure how much gas is, will try and keep an eye the next time I vote

**Comment by Rigorously** [comment] 2024-04-03 09:20
See, other people observe the same: https://github.com/anoma/namada/issues/2988

**Comment by opsecx** [comment] 2024-04-03 09:48
I don't doubt that. Does not happen here though for some reason.

**Comment by zaki9501** [comment] 2024-04-04 10:16
i thought im the only who is paying this much of fee just for the vote

**Comment by grarco** [comment] 2024-08-22 14:20
This is somewhat old. I've tried to reproduce this on the latest version `v0.43.0` and wasn't able. These are the costs I've got:

| Address    | Gas cost |
| -------- | ------- |
| Implicit  | 49885    |
| Established | 49743     |
| Validator (self-bond)    | 49750    |

So the gas cost to vote on a proposal from an implicit address is still higher than the cost for an established address, but the difference is minimal. We've changed quite a few things in terms of gas in the last releases compared to the version on which this bug was found, including: gas prices, gas dividers, accounting mechanism. Some of these changes might have fixed this issue.

I'm closing this for now since it seems to be solved but feel free to reopen it if needed.

**Closed by grarco** 2024-08-22 14:20 UTC
Labels: bug
