### ISSUE TITLE
Stop namadan if --path checksum does not match --hash

### ISSUE THREAD

**Issue by Rigorously** [anoma/namada#4108] opened 2024-11-28 20:32 UTC
Several validators failed to upgrade from v0.45.1 to v0.46, because they supplied a HTML file (wget github page) instead of JSON file.

After running `namadan-0.46.0 ledger run --height 182000 --path $MIGRATION_JSON --hash acadd7d124804448b3c7f7b3dc0c3bc536fe6dbd1594757d5a992d47ecacc5c6` their nodes came in an inconsistent state and they need to sync from scratch. This could perhaps be prevented by having namadan verify the $MIGRATION_JSON.

**Comment by tzemanovic** [comment] 2024-11-29 10:18
if the hash doesn't match the migration file the node will crash with:

```
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value:
   0: Provided hash did not match the contents at the specified path.
```

so the issue is somewhere else

**Comment by Rigorously** [comment] 2024-11-29 11:59
The crash because of the hash mismatch implies a restart, and restarts currently cause a panic: #4112 .

**Comment by sug0** [comment] 2024-12-01 09:49
can we close this?

**Comment by brentstone** [comment] 2024-12-01 10:51
@sug0 @tzemanovic @grarco your choice if we can close

**Comment by sug0** [comment] 2024-12-01 11:05
@tzemanovic confirmed that we halt on an invalid hash as soon as we boot up. the only explanation for the hash check to have succeeded is if the user provided a checksum they computed themselves over the faulty file.

**Closed by sug0** 2024-12-01 11:05 UTC
Labels: enhancement
