### ISSUE TITLE
Refund failed when IBC unshielded transfer failed

### ISSUE THREAD

**Issue by yito88** [anoma/namada#3619] opened 2024-08-12 19:04 UTC
When transferring an IBC token back to the source chain from a shielded account, the refund failed because the MASP VP rejected it.
The token from the source chain was minted in Namada. So, when transferring back to the source chain, the token is burned on the source Namada. After the IBC transfer has failed by a timeout or a receiving error, it should be refunded by minting it again in Namada.

**Comment by murisi** [comment] 2024-08-13 07:33
Agreed. The plan I'd had for resolving this was as follows:
* Make E2E tests to test that refunds for shielded transactions work when the sender chain is not the source of the IBC token
  * Ideally these tests should cover the cases when the refund is caused by an acknowledgement error, timeout, or timeout on close
* Add handlers in the MASP VP for `PacketMsg::Ack` (only when it is an error), `PacketMsg::Timeout`, and `PacketMsg::TimeoutOnClose`:
    * In the case where the sender chain is not the source of the IBC token, they must increase the IBC internal address PRE balance by the amount stated in the packet
      * Doing this will ensure that there are enough funds in the IBC internal address for the refunding MASP `Transaction` to draw from and should fix the failures that you discovered above
      * The final code should look similar to https://github.com/anoma/namada/blob/d2e4fd9a0b68ad6dee33134aee4a32f232296824/crates/ibc/src/lib.rs#L521-L555 once it's done, but with `!is_receiver_chain_source_str` replaced by `!is_sender_chain_source_str`.

**Closed** 2024-08-20 09:46 UTC
Labels: bug, IBC, MASP
