### ISSUE TITLE
Asset threshold of selected conversion for asset type is 0

### ISSUE THREAD

**Issue by encipher88** [anoma/namada#3040] opened 2024-04-09 13:45 UTC
`namadac balance --owner enbit88`

```
Last committed epoch: 86
converting current asset type to latest asset type...
Asset threshold of selected conversion for asset type bfe4922fe3da46887eaeedfc37dfd286c11f961cc37dbe285dd08dc241539020 is 0, this is a bug, please report it.
The application panicked (crashed).
Message:  attempt to divide by zero
Location: /home/runner/work/namada/namada/crates/sdk/src/masp.rs:1474

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
```

**Comment by brentstone** [comment] 2024-04-09 13:48
Thanks, this is a duplicate of #3010.

**Closed by brentstone** 2024-04-09 13:48 UTC
Labels: bug

**Comment by encipher88** [comment] 2024-04-09 13:58
> Thanks, this is a duplicate of #3010.

yes i delete old shield.dat and now working
