### ISSUE TITLE
Track MASP anchor hashes in app hash

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2794] opened 2024-03-04 08:48 UTC
Per discussion

Also may need to do this for the commitment tree.

**Comment by brentstone** [comment] 2024-04-06 07:49
Also consider doing this for the commitment tree

**Comment by grarco** [comment] 2024-04-06 14:00
Yes this was intended for both the trees even though the conversion one should have already been addressed in the pr mentioned above

**Comment by cwgoes** [comment] 2024-04-24 09:57
We should do this in phase 1, otherwise it might require a hard fork.

**Comment by grarco** [comment] 2024-04-24 10:01
Yes should be quick

**Closed** 2024-04-27 00:49 UTC
Labels: MASP, pre-mainnet, breaking: protocol
