### ISSUE TITLE
my node gradually loses peers

### ISSUE THREAD

**Issue by encipher88** [anoma/namada#963] opened 2022-12-24 14:58 UTC
Thank you for the bug report. Please provide any information that may be relevant to the issue you're experiencing.

my node gradually loses peers during the day and then the p2p module just endlessly looks for peers. only reboot helps

root@linux ~ # sudo journalctl -u namadad -f -o cat
I[2022-12-24|15:34:44.499] Ensure peers                                 module=pex numOutPeers=0 numInPeers=0 numDialing=0 numToDial=10
I[2022-12-24|15:34:44.500] Dialing peer                                 module=p2p address=e3f86246a68f78b9c4069120b26420970106d164@178.62.44.130:26656
I[2022-12-24|15:34:44.500] Dialing peer                                 module=p2p address=241c1840696e12e8f6ad4b01eeb13254aa748536@162.19.169.12:26656
I[2022-12-24|15:35:14.500] Ensure peers                                 module=pex numOutPeers=0 numInPeers=0 numDialing=0 numToDial=10
I[2022-12-24|15:35:44.499] Ensure peers                                 module=pex numOutPeers=0 numInPeers=0 numDialing=0 numToDial=10
I[2022-12-24|15:36:14.494] Saving AddrBook to file                      module=p2p book=/root/.namada/public-testnet-1.0.05ab4adb9db/tendermint/config/addrbook.json size=28
I[2022-12-24|15:36:14.500] Ensure peers                                 module=pex numOutPeers=0 numInPeers=0 numDialing=0 numToDial=10
I[2022-12-24|15:36:14.516] Dialing peer                                 module=p2p address=993a2fdea2d0090b4d2e0ce9317c349c28bc033f@212.51.129.108:26656
I[2022-12-24|15:36:14.516] Dialing peer                                 module=p2p address=96d2fc05302c1c3fc38e25b632ffe3b8db507406@159.203.12.165:26656
I[2022-12-24|15:36:14.578] Reconnecting to peer                         module=p2p addr=993a2fdea2d0090b4d2e0ce9317c349c28bc033f@212.51.129.108:26656
^[[A^[[A^C
root@linux ~ # sudo systemctl restart namadad && sudo journalctl -u namadad -f -o cat
I[2022-12-24|15:36:44.499] Dialing peer                                 module=p2p address=e15353176a79c9f97b62cddd65eed2ef17d9f6be@99.230.250.213:26656
Stopping namada...
2022-12-24T14:36:48.041188Z  INFO namada_apps::node::ledger::abortable: Received termination signal, exiting...
2022-12-24T14:36:48.041474Z  INFO namada_apps::node::ledger::tendermint_node: Shutting down Tendermint node...
2022-12-24T14:36:48.098877Z  INFO namada_apps::node::ledger: Tendermint node is no longer running.
2022-12-24T14:36:48.098886Z  INFO namada_apps::node::ledger: Shutting down ABCI server...
2022-12-24T14:36:48.098920Z  INFO namada_apps::node::ledger: Namada ledger node has shut down.
namadad.service: Succeeded.
Stopped namada.
Started namada.
2022-12-24T14:36:49.308062Z  INFO namada_apps::cli::context: Chain ID: public-testnet-1.0.05ab4adb9db
2022-12-24T14:36:49.329823Z  INFO namada_apps::node::ledger: Available logical cores: 12
2022-12-24T14:36:49.329830Z  INFO namada_apps::node::ledger: Using 6 threads for Rayon.
2022-12-24T14:36:49.329832Z  INFO namada_apps::node::ledger: Using 6 threads for Tokio.
2022-12-24T14:36:49.332160Z  INFO namada_apps::node::ledger: VP WASM compilation cache size not configured, using 1/6 of available memory.
2022-12-24T14:36:49.550371Z  INFO namada_apps::node::ledger: Available memory: 62.76 GiB
2022-12-24T14:36:49.550399Z  INFO namada_apps::node::ledger: VP WASM compilation cache size: 10.46 GiB
2022-12-24T14:36:49.550403Z  INFO namada_apps::node::ledger: Tx WASM compilation cache size not configured, using 1/6 of available memory.
2022-12-24T14:36:49.550406Z  INFO namada_apps::node::ledger: Tx WASM compilation cache size: 10.46 GiB
2022-12-24T14:36:49.550409Z  INFO namada_apps::node::ledger: Block cache size not configured, using 1/3 of available memory.
2022-12-24T14:36:49.550412Z  INFO namada_apps::node::ledger: RocksDB block cache size: 20.92 GiB
2022-12-24T14:36:49.576085Z  INFO namada_apps::node::ledger::storage::rocksdb: Using 3 compactions threads for RocksDB.
2022-12-24T14:36:49.576272Z DEBUG namada_apps::node::ledger::storage::rocksdb::imp: Current NOFILE limit, soft=65535, hard=65535
2022-12-24T14:36:49.576276Z DEBUG namada_apps::node::ledger::storage::rocksdb::imp: NOFILE limit already large enough, not attempting to increase
2022-12-24T14:36:49.581218Z  INFO namada_apps::node::ledger::tendermint_node: Tendermint node started
2022-12-24T14:36:49.695857Z DEBUG namada_core::ledger::storage: storage read key #atest1v4ehgw36xaryysfsx5unvve4g5my2vjz89p52sjxxgenzd348yuyyv3hg3pnjs35g5unvde4ca36y5/conv
I[2022-12-24|15:36:49.811] service start                                module=proxy msg="Starting multiAppConn service" impl=multiAppConn
I[2022-12-24|15:36:49.811] service start                                module=abci-client connection=query msg="Starting socketClient service" impl=socketClient
E[2022-12-24|15:36:49.811] abci.socketClient failed to connect to 127.0.0.1:26658.  Retrying after 3s... module=abci-client connection=query err="dial tcp 127.0.0.1:26658: connect: connection refused"
2022-12-24T14:36:49.821327Z DEBUG namada_core::ledger::storage: Loaded storage from DB
2022-12-24T14:36:49.821493Z  INFO namada_apps::node::ledger: Namada ledger node started.
2022-12-24T14:36:49.821514Z  INFO namada_apps::node::ledger: This node is not a validator
I[2022-12-24|15:36:52.812] service start                                module=abci-client connection=snapshot msg="Starting socketClient service" impl=socketClient
I[2022-12-24|15:36:52.812] service start                                module=abci-client connection=mempool msg="Starting socketClient service" impl=socketClient
I[2022-12-24|15:36:52.812] service start                                module=abci-client connection=consensus msg="Starting socketClient service" impl=socketClient
I[2022-12-24|15:36:52.812] service start                                module=events msg="Starting EventBus service" impl=EventBus
I[2022-12-24|15:36:52.812] service start                                module=pubsub msg="Starting PubSub service" impl=PubSub
I[2022-12-24|15:36:52.967] service start                                module=txindex msg="Starting IndexerService service" impl=IndexerService
2022-12-24T14:36:52.967202Z DEBUG tower::buffer::worker: service.ready=true processing request
2022-12-24T14:36:52.967283Z  INFO namada_apps::node::ledger::shell: Last state root hash: 435fde477ea3709402a57433c366485f18df8f63722a20f91f6cf827e13f7566, height: 11694
I[2022-12-24|15:36:52.967] ABCI Handshake App Info                      module=consensus height=11694 hash=435FDE477EA3709402A57433C366485F18DF8F63722A20F91F6CF827E13F7566 software-version= protocol-version=0
I[2022-12-24|15:36:52.967] ABCI Replay Blocks                           module=consensus appHeight=11694 storeHeight=11694 stateHeight=11693
I[2022-12-24|15:36:52.967] Replay last block using mock app             module=consensus
I[2022-12-24|15:36:53.069] executed block                               module=consensus height=11694 num_valid_txs=102 num_invalid_txs=0
I[2022-12-24|15:36:53.074] committed state                              module=consensus height=11694 num_txs=102 app_hash=435FDE477EA3709402A57433C366485F18DF8F63722A20F91F6CF827E13F7566
I[2022-12-24|15:36:53.121] Completed ABCI Handshake - Tendermint and App are synced module=consensus appHeight=11694 appHash=435FDE477EA3709402A57433C366485F18DF8F63722A20F91F6CF827E13F7566
I[2022-12-24|15:36:53.121] Version info                                 module=main tendermint_version=v0.1.4-abciplus block=11 p2p=8
I[2022-12-24|15:36:53.121] This node is a validator                     module=consensus addr=941E042F17B4EBC038F57B6E65AFD31B7D489C51 pubKey=PubKeyEd25519{2A750D5DBEE076FB4D5332E877E51A7FE2A35389754EBEF33A2CA01971C6FCFD}
I[2022-12-24|15:36:53.128] indexed block                                module=txindex height=11694
I[2022-12-24|15:36:53.152] P2P Node ID                                  module=p2p ID=a74b1eb7bf31242419af2e1a0d6f42e97d574a71 file=/root/.namada/public-testnet-1.0.05ab4adb9db/tendermint/config/node_key.json
I[2022-12-24|15:36:53.152] Adding persistent peers                      module=p2p addrs="[tcp://2e819155cf873df973445168b4c50d44a9ef2ab5@51.38.53.103:26656 tcp://ede26688e04fe40dc5f0b253131ffa509a2e0cfa@138.197.160.81:26656 tcp://6e3f19e39961a59ad200a61a8bd30eb01f5a7c72@167.71.55.25:26656 tcp://e3f86246a68f78b9c4069120b26420970106d164@178.62.44.130:26656 tcp://01b6140c9837d9d1a6a62b95686563759e96447d@65.108.76.60:26656 tcp://beecdc943ae4b425251cc62e1c5c52cc2f4425a5@63.32.210.222:26656 tcp://993a2fdea2d0090b4d2e0ce9317c349c28bc033f@212.51.129.108:26656 tcp://e15353176a79c9f97b62cddd65eed2ef17d9f6be@99.230.250.213:26656 tcp://f3ed5a75241ae8a240a6ff2081c0299cc4c68860@18.202.229.149:26656 tcp://15fb65a80877e902f124f9d1c553518832e840e4@3.34.17.147:26656 tcp://264c52408428af49d2e223e039e0543135112ba3@37.120.245.74:26656 tcp://7959e9dd23424ccdef795a443a89a3536cc6021b@77.241.194.155:26656 tcp://4d6cfd5613a354081954299c098e72bf998019eb@34.159.225.73:26656 tcp://241c1840696e12e8f6ad4b01eeb13254aa748536@162.19.169.12:26656 tcp://6a802c5cfa138649a513e5e55a7766c82cc0cf45@188.166.202.55:26656 tcp://1ea7b1b8953cd7e9233d63b47dccb336c89f3596@65.108.207.160:26656 tcp://08e154e213407f0ecc495fda5bbfecb50f91a9dc@95.217.193.182:26656 tcp://a8fad546eb4302b67b3bb6112e8ff16bab2dcfef@143.244.196.53:26656 tcp://740b702b15e6e5a69252e62bb866b63b8c563fb7@93.115.25.19:26656 tcp://09f0c75f8808d32353fa5dcf7ef3283cb4058771@157.230.24.247:26656 tcp://e72449a181774fbbb42d1485c09f0f83107ccc11@65.108.199.210:26656 tcp://30b6349310cf2394fabc69e55008df83d6bdaf72@34.159.27.16:26656 tcp://9f4faffebf3a18e828eb0141efef84b904977a38@65.108.225.158:26656 tcp://dd103f8d040af57edeee0e4f71fab1ecbce8814d@185.172.191.12:26656 tcp://5b6a4213b4dc05a68082ade4c01b27e0acf4c562@147.182.159.116:26656 tcp://e6f5b4a6d816d0997b4882620976f215eccc9095@65.21.163.229:26656 tcp://6d575cad026414aac85c7be03fc3593c7dc3d3e0@80.64.208.172:26656 tcp://96d2fc05302c1c3fc38e25b632ffe3b8db507406@159.203.12.165:26656]"
I[2022-12-24|15:36:53.152] Adding unconditional peer ids                module=p2p ids=[]
I[2022-12-24|15:36:53.152] Add our address to book                      module=p2p book=/root/.namada/public-testnet-1.0.05ab4adb9db/tendermint/config/addrbook.json addr=a74b1eb7bf31242419af2e1a0d6f42e97d574a71@0.0.0.0:26656
I[2022-12-24|15:36:53.152] service start                                module=main msg="Starting Node service" impl=Node
I[2022-12-24|15:36:53.152] service start                                module=p2p msg="Starting P2P Switch service" impl="P2P Switch"
I[2022-12-24|15:36:53.152] service start                                module=blockchain msg="Starting Reactor service" impl=Reactor
I[2022-12-24|15:36:53.152] service start                                module=blockchain msg="Starting BlockPool service" impl=BlockPool
I[2022-12-24|15:36:53.152] service start                                module=consensus msg="Starting Consensus service" impl=ConsensusReactor
I[2022-12-24|15:36:53.152] serve                                        module=rpc-server msg="Starting RPC HTTP server on 127.0.0.1:26657"
I[2022-12-24|15:36:53.152] Reactor                                      module=consensus waitSync=true
I[2022-12-24|15:36:53.152] service start                                module=evidence msg="Starting Evidence service" impl=Evidence
I[2022-12-24|15:36:53.152] service start                                module=statesync msg="Starting StateSync service" impl=StateSync
I[2022-12-24|15:36:53.152] service start                                module=pex msg="Starting PEX service" impl=PEX
I[2022-12-24|15:36:53.152] service start                                module=p2p book=/root/.namada/public-testnet-1.0.05ab4adb9db/tendermint/config/addrbook.json msg="Starting AddrBook service" impl=AddrBook
I[2022-12-24|15:36:53.153] Saving AddrBook to file                      module=p2p book=/root/.namada/public-testnet-1.0.05ab4adb9db/tendermint/config/addrbook.json size=28
I[2022-12-24|15:36:53.153] Ensure peers                                 module=pex numOutPeers=0 numInPeers=0 numDialing=0 numToDial=10
I[2022-12-24|15:36:53.160] Started node                                 module=main nodeInfo="{ProtocolVersion:{P2P:8 Block:11 App:0} DefaultNodeID:a74b1eb7bf31242419af2e1a0d6f42e97d574a71 ListenAddr:tcp://0.0.0.0:26656 Network:public-testnet-1.0.05ab4adb9db Version:v0.1.4-abciplus Channels:40202122233038606100 Moniker:linux Other:{TxIndex:on RPCAddress:tcp://127.0.0.1:26657}}"
I[2022-12-24|15:36:53.160] Dialing peer                                 module=p2p address=08e154e213407f0ecc495fda5bbfecb50f91a9dc@95.217.193.182:26656
I[2022-12-24|15:36:53.160] Dialing peer                                 module=p2p address=6a802c5cfa138649a513e5e55a7766c82cc0cf45@188.166.202.55:26656
I[2022-12-24|15:36:53.160] Dialing peer                                 module=p2p address=e15353176a79c9f97b62cddd65eed2ef17d9f6be@99.230.250.213:26656
I[2022-12-24|15:36:53.160] Dialing peer                                 module=p2p address=1ea7b1b8953cd7e9233d63b47dccb336c89f3596@65.108.207.160:26656
I[2022-12-24|15:36:53.160] Dialing peer                                 module=p2p address=2e819155cf873df973445168b4c50d44a9ef2ab5@51.38.53.103:26656
I[2022-12-24|15:36:53.160] Dialing peer                                 module=p2p address=e72449a181774fbbb42d1485c09f0f83107ccc11@65.108.199.210:26656
I[2022-12-24|15:36:53.160] Dialing peer                                 module=p2p address=01b6140c9837d9d1a6a62b95686563759e96447d@65.108.76.60:26656
I[2022-12-24|15:36:53.160] Dialing peer                                 module=p2p address=6e3f19e39961a59ad200a61a8bd30eb01f5a7c72@167.71.55.25:26656
I[2022-12-24|15:36:53.160] Dialing peer                                 module=p2p address=15fb65a80877e902f124f9d1c553518832e840e4@3.34.17.147:26656
I[2022-12-24|15:36:53.160] Dialing peer                                 module=p2p address=740b702b15e6e5a69252e62bb866b63b8c563fb7@93.115.25.19:26656
I[2022-12-24|15:36:53.299] service start                                module=p2p peer=6a802c5cfa138649a513e5e55a7766c82cc0cf45@188.166.202.55:26656 msg="Starting Peer service" impl="Peer{MConn{188.166.202.55:26656} 6a802c5cfa138649a513e5e55a7766c82cc0cf45 out}"
I[2022-12-24|15:36:53.299] service start                                module=p2p peer=6a802c5cfa138649a513e5e55a7766c82cc0cf45@188.166.202.55:26656 msg="Starting MConnection service" impl=MConn{188.166.202.55:26656}

and after 2 minutes 

I[2022-12-24|15:57:51.742] indexed block                                module=txindex height=11817
I[2022-12-24|15:57:52.146] Error reconnecting to peer. Trying again     module=p2p tries=6 err="dial tcp 34.159.27.16:26656: i/o timeout" addr=30b6349310cf2394fabc69e55008df83d6bdaf72@34.159.27.16:26656
I[2022-12-24|15:57:53.160] Ensure peers                                 module=pex numOutPeers=10 numInPeers=1 numDialing=0 numToDial=0
I[2022-12-24|15:57:58.279] Timed out                                    module=consensus dur=6.544006674s height=11818 round=0 step=RoundStepNewHeight
I[2022-12-24|15:57:59.377] received proposal                            module=consensus proposal="Proposal{11818/0 (FF0657AAACD32F756152117B77B6BB0EFA8AB00D3367746304A9A3F94DF82AFB:297:DD4F747E5A4C, -1) 231826085B7E @ 2022-12-24T14:57:58.914324983Z}"
I[2022-12-24|15:58:00.693] Dialing peer                                 module=p2p address=4d6cfd5613a354081954299c098e72bf998019eb@34.159.225.73:26656
I[2022-12-24|15:58:01.280] Timed out                                    module=consensus dur=3s height=11818 round=0 step=RoundStepPropose
I[2022-12-24|15:58:01.693] Error reconnecting to peer. Trying again     module=p2p tries=6 err="dial tcp 34.159.225.73:26656: i/o timeout" addr=4d6cfd5613a354081954299c098e72bf998019eb@34.159.225.73:26656
I[2022-12-24|15:58:03.218] Timed out                                    module=consensus dur=1s height=11818 round=0 step=RoundStepPrecommitWait
I[2022-12-24|15:58:03.700] received proposal                            module=consensus proposal="Proposal{11818/1 (884028FD11E1FA26A1E6FCC3CDD24E6C5C53E1668481EF1F5E27CB164BB4801F:252:ACC47D40E5F5, -1) EDFBF03C2EC4 @ 2022-12-24T14:58:03.520984761Z}"
I[2022-12-24|15:58:06.718] Timed out                                    module=consensus dur=3.5s height=11818 round=1 step=RoundStepPropose
I[2022-12-24|15:58:07.095] received complete proposal block             module=consensus height=11818 hash=884028FD11E1FA26A1E6FCC3CDD24E6C5C53E1668481EF1F5E27CB164BB4801F

**Comment by tzemanovic** [comment] 2022-12-30 09:14
p2p is handled by tendermint go - we're temporarily on a fork (https://github.com/heliaxdev/tendermint/releases/tag/v0.1.4-abciplus) which I suspect is likely to be the cause of this

**Comment by adrianbrink** [comment] 2023-01-11 08:04
What hardware are you on and do you have things like NAT punching enabled?

I'm closing this for now, since this seems to be an isolated problem and it lies in the Tendermint implementation. If you experience this again, please comment on this issue.

**Closed by adrianbrink** 2023-01-11 08:04 UTC
Labels: bug
