### ISSUE TITLE
all of "namadac" features resulted error

### ISSUE THREAD

**Issue by hubofvalley** [anoma/namada#2703] opened 2024-02-22 21:14 UTC
latest version V0.31.6 contains errors. **all of "namadac" features resulted error**

one of example : 
command : ```namadac balance --owner $WALLET```
result : 
```Failed to query node status with error:
   0: HTTP error
   1: builder error for url (tcp://0.0.0.0:26657): URL scheme is not allowed

Location:
   /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Error:
   0: Querying error: Error in the query: Failed to query node status with error:
         0: HTTP error
         1: builder error for url (tcp://0.0.0.0:26657): URL scheme is not allowed

      Location:
         /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10

      Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
      Run with RUST_BACKTRACE=full to include source snippets.
   1: Error in the query: Failed to query node status with error:
         0: HTTP error
         1: builder error for url (tcp://0.0.0.0:26657): URL scheme is not allowed

      Location:
         /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10

      Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
      Run with RUST_BACKTRACE=full to include source snippets.

Location:
   /home/runner/work/namada/namada/crates/apps/src/lib/cli/client.rs:528

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.```

**Comment by brentstone** [comment] 2024-02-22 23:47
Closing as this is a duplicate of #2702.

**Closed by brentstone** 2024-02-22 23:47 UTC
Labels: bug
