### ISSUE TITLE
Unjail Transaction Rejections by Small Validators

### ISSUE THREAD

**Issue by zaki9501** [anoma/namada#2998] opened 2024-04-03 12:30 UTC
Issue Report: Unjail Transaction Rejections by Small Validators

Description:
I've observed a recurring pattern of unjail transactions being rejected by small validators, particularly those in the below-capacity set at the next epoch. This issue raises concerns about transaction processing reliability and the potential impact on network stability.

namadac unjail-validator --validator $validator address --memo $MEMO

Looking-up public key of tnam1qxy9m5nywn8r7nzwxex7ng7ta7dzmsfjv5k3qm65 from the ledger...
Enter your decryption password: 
Transaction added to mempool.
Wrapper transaction hash: 7A0D5654335B56C08A7B33AF98FE9FDC628E7448E5442A7EB708EC30D9B79247
Inner transaction hash: FCC54E46F873D72D8223274B8977BF59EAE12972A8D2DAC9BD3EDB477C847B92
Wrapper transaction accepted at height 290849. Used 23 gas.
Waiting for inner transaction result...
Transaction was rejected by VPs: [
  "tnam1qxu5d99xqgly0nr5gv3gylcf2yspx6fxrgjq40as"
].
Changed keys: [
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxu5d99xqgly0nr5gv3gylcf2yspx6fxrgjq40as/state/last_update",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxu5d99xqgly0nr5gv3gylcf2yspx6fxrgjq40as/state/lazy_map/data/000000000004O",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxy9m5nywn8r7nzwxex7ng7ta7dzmsfjv5k3qm65/state/last_update",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxy9m5nywn8r7nzwxex7ng7ta7dzmsfjv5k3qm65/state/lazy_map/data/000000000004E",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxy9m5nywn8r7nzwxex7ng7ta7dzmsfjv5k3qm65/state/lazy_map/data/000000000004G",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxy9m5nywn8r7nzwxex7ng7ta7dzmsfjv5k3qm65/state/lazy_map/data/000000000004O",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxy9m5nywn8r7nzwxex7ng7ta7dzmsfjv5k3qm65/state/oldest_epoch",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_set_positions/lazy_map/data/000000000004O/data/#tnam1qxu5d99xqgly0nr5gv3gylcf2yspx6fxrgjq40as",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_set_positions/lazy_map/data/000000000004O/data/#tnam1qxy9m5nywn8r7nzwxex7ng7ta7dzmsfjv5k3qm65",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_sets/below_capacity/lazy_map/data/000000000004O/data/FVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVH356NVG/data/0000000000010",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_sets/consensus/lazy_map/data/000000000004O/data/000000000000000000000000000000000000000000000ESQP800/data/0000000000002",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_sets/consensus/lazy_map/data/000000000004O/data/000000000000000000000000000000000000000000006JE0O6G0/data/0000000000000"
]

Details:

Observation: Unjail transactions, intended to release validators from jail status, are consistently rejected by small validators.
Validator Set Dynamics: Rejections predominantly originate from validators expected to be in the below-capacity set at the next epoch.
Rejection Context: Small validators rejecting unjail transactions may indicate capacity constraints, resource limitations, economic incentives, or network dynamics influencing transaction processing decisions.
Potential Causes:

Capacity Constraints: Small validators may lack sufficient resources or bandwidth to handle additional transactions, leading to rejections.
Resource Limitations: Limited computing power or memory could prevent small validators from processing transactions efficiently.
Economic Incentives: Validators may prioritize transactions that offer higher rewards or benefits, potentially rejecting unjail transactions if they perceive minimal gains.
Network Dynamics: Congestion, latency, or network partitioning may affect transaction processing decisions, especially for validators with limited capacity.
Recommended Actions:

version: v0.32.1
Epoch: 74
Transaction Hashes: Wrapper transaction hash: 7A0D5654335B56C08A7B33AF98FE9FDC628E7448E5442A7EB708EC30D9B79247
Inner transaction hash: FCC54E46F873D72D8223274B8977BF59EAE12972A8D2DAC9BD3EDB477C847B92

**Comment by Rigorously** [comment] 2024-04-03 16:22
Based on reports from other users, small validators rejecting `unjail` transactions is a pattern. But it could be a symptom rather than the cause. In some cases the client gives unreliable error messages. Maybe there is a different underlying problem that makes the client return a small validator as the reason for failure.

**Comment by zaki9501** [comment] 2024-04-03 17:15
hmmm, interesting. curious to know what could be the real cause then

**Comment by brentstone** [comment] 2024-04-03 18:54
Thanks for the issue report, will look into this very soon.

**Comment by brentstone** [comment] 2024-04-05 06:59
Going to close this issue now. This should've been fixed for the SE, and I am debugging with some other users, but the next release (targeted toward mainnet) is going to include a VP refactor that will resolve this behavior anyway. We are very likely not going to include a temporary fix for the SE for this and are focusing engineering time on mainnet instead.

**Closed by brentstone** 2024-04-05 06:59 UTC
Labels: bug

**Comment by farhanw1833** [comment] 2024-04-05 17:34
> Going to close this issue now. This should've been fixed for the SE, and I am debugging with some other users, but the next release (targeted toward mainnet) is going to include a VP refactor that will resolve this behavior anyway. We are very likely not going to include a temporary fix for the SE for this and are focusing engineering time on mainnet instead.

then we cant unjail aur validator. we loss to much uptime already

**Comment by zaki9501** [comment] 2024-04-09 01:04
looks like the issue is with  `vp_wasm_cache` after deleting a folder some of the validator are able to unjail without any vp rejection

**Comment by pero85v** [comment] 2024-04-09 17:07
> looks like the issue is with `vp_wasm_cache` after deleting a folder some of the validator are able to unjail without any vp rejection
It didn't work for me. Removed `tx_wasm_cache` and `vp_wasm_cache`, restarted the validator. The problem with unjail vp rejection still remains.
The vp rejection comes from small validators. And I had several times in a row vp rejection was from a validator that was not in the validator set because of the size of the steak.

```
Transaction was rejected by VPs: [
  "tnam1qymkz6d4nny4dwh9gvgzm5awjy9ahyhjzsrzlyh3"
].
Changed keys: [
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1q9as8pmadedmlckdxg0xeady6fgkqzwppcgv7szl/state/last_update",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1q9as8pmadedmlckdxg0xeady6fgkqzwppcgv7szl/state/lazy_map/data/0000000000014",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1q9as8pmadedmlckdxg0xeady6fgkqzwppcgv7szl/state/lazy_map/data/000000000001A",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1q9as8pmadedmlckdxg0xeady6fgkqzwppcgv7szl/state/lazy_map/data/000000000001C",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1q9as8pmadedmlckdxg0xeady6fgkqzwppcgv7szl/state/lazy_map/data/0000000000058",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1q9as8pmadedmlckdxg0xeady6fgkqzwppcgv7szl/state/lazy_map/data/000000000005G",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1q9as8pmadedmlckdxg0xeady6fgkqzwppcgv7szl/state/oldest_epoch",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qymkz6d4nny4dwh9gvgzm5awjy9ahyhjzsrzlyh3/state/last_update",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qymkz6d4nny4dwh9gvgzm5awjy9ahyhjzsrzlyh3/state/lazy_map/data/000000000005G",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_set_positions/lazy_map/data/000000000005G/data/#tnam1q9as8pmadedmlckdxg0xeady6fgkqzwppcgv7szl",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_set_positions/lazy_map/data/000000000005G/data/#tnam1qymkz6d4nny4dwh9gvgzm5awjy9ahyhjzsrzlyh3",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_sets/below_capacity/lazy_map/data/000000000005G/data/FVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVH356NVG/data/0000000000014",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_sets/consensus/lazy_map/data/000000000005G/data/000000000000000000000000000000000000000000000ESQP800/data/0000000000002",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_sets/consensus/lazy_map/data/000000000005G/data/00000000000000000000000000000000000000000000DH0SD400/data/0000000000000"
]
```
```
namadac validator-state --validator tnam1qymkz6d4nny4dwh9gvgzm5awjy9ahyhjzsrzlyh3 --node http://127.0.0.1:26857
Validator tnam1qymkz6d4nny4dwh9gvgzm5awjy9ahyhjzsrzlyh3 is in the below-capacity set
```
My validator stays in jail.
