### ISSUE TITLE
IBC TRANSFER TO OTHER  COSMOS CHAIN DOES NOT REFLECT IN BALANCE

### ISSUE THREAD

**Issue by Jaytechent** [anoma/namada#3099] opened 2024-04-18 23:57 UTC
I  transfer nam token using ibc transfer and i check the other wallet but could not find it...

command used with the cli below

```namadac ibc-transfer --amount 100 --source jaytechent --receiver tnam1qrgq23xz4zrhdsjmvy32pvf6thpf80refvqtyzpt  --token naan --channel-id channel-40 ``` 

The transcation went succefully and the token was removed but the reciever did not get the token

**Comment by McDaan** [comment] 2024-04-19 04:57
This is not a bug. Duplicate of [3007](https://github.com/anoma/namada/issues/3007).

Refer to https://github.com/anoma/namada/issues/3007#issuecomment-2063530882 for further clarification.

**Closed** 2024-04-19 10:30 UTC
Labels: bug
