### ISSUE TITLE
"namadaw balance --owner xxx" throws decoding errors

### ISSUE THREAD

**Issue by adrianbrink** [anoma/namada#831] opened 2022-11-28 12:55 UTC
```
sammy@sammy:~/namada$ namadac balance --owner adrian-key
2022-11-28T12:54:39.479451Z  INFO namada_apps::cli::context: Chain ID: qc-testnet-4.1.4df153b1216ae81
Token Kartoffel
Skipping a value for key #atest1v4ehgw36gep5ysecxq6nyv3jg3zygv3e89qn2vp48pryxsf4xpznvve5gvmy23fs89pryvf5a6ht90/?. Error in decoding: Not all bytes read
No balances owned by adrian-key
Token DOT
Skipping a value for key #atest1v4ehgw36gg6nvs2zgfpyxsfjgc65yv6pxy6nwwfsxgungdzrggeyzv35gveyxsjyxymyz335hur2jn/?. Error in decoding: Not all bytes read
No balances owned by adrian-key
Token Apfel
Skipping a value for key #atest1v4ehgw36gfryydj9g3p5zv3kg9znyd358ycnzsfcggc5gvecgc6ygs2rxv6ry3zpg4zrwdfeumqcz9/?. Error in decoding: Not all bytes read
No balances owned by adrian-key
Token ETH
Skipping a value for key #atest1v4ehgw36xqmr2d3nx3ryvd2xxgmrq33j8qcns33sxezrgv6zxdzrydjrxveygd2yxumrsdpsf9jc2p/?. Error in decoding: Not all bytes read
No balances owned by adrian-key
Token NAM
Skipping a value for key #atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5/?. Error in decoding: Not all bytes read
: 10, owned by adrian-key
Token BTC
Skipping a value for key #atest1v4ehgw36xdzryve5gsc52veeg5cnsv2yx5eygvp38qcrvd29xy6rys6p8yc5xvp4xfpy2v694wgwcp/?. Error in decoding: Not all bytes read
No balances owned by adrian-key
Token Schnitzel
Skipping a value for key #atest1v4ehgw36xue5xvf5xvuyzvpjx5un2v3k8qeyvd3cxdqns32p89rrxd6xx9zngvpegccnzs699rdnnt/?. Error in decoding: Not all bytes read
No balances owned by adrian-key
```

This is on testnet 4.1

**Comment by tzemanovic** [comment] 2022-11-28 13:21
duplicate of #758

**Closed by tzemanovic** 2022-11-28 13:21 UTC
Labels: bug
