### ISSUE TITLE
Shielded actions is broken V0.32.1

### ISSUE THREAD

**Issue by monleru** [anoma/namada#2967] opened 2024-03-27 20:37 UTC
Shielded actions is broken.

When adding a new shield address and a new shield payment address, and successfully funding it, the user can see their balance after shielded-sync:

`namadac balance --owner test-test --node $NODE                            
Last committed epoch: 61
naan : 1` 

However, after attempting to send a transaction, it is rejected due to insufficient balance at the source:

`Transaction added to mempool.
Wrapper transaction hash: CE2ED8EB614F98FAF65FC5EE27639BC4D4588A9B7A8AF070340D453470242AE2
Inner transaction hash: A9B9AE05D66B82EF1A014DD719587054BD99AEB6637E1BEB849950CA9A71F7D5
Wrapper transaction accepted at height 239377. Used 70 gas.
Waiting for inner transaction result...
Transaction was rejected by VPs: [
  "tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah"
].
Changed keys: [
  "#tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah/commitment_tree",
  "#tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah/nullifiers/48609694D38C990E101A710C5F97014E1AA146804640B57E1BAACD6FC479129B",
  "#tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv/#tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee/balance/#tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah",
  "#tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv/#tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee/balance/#tnam1qpvz9gppxe9jzjzhfs90kmtea896s5sd6qag6ez4"
]` 

Upon receiving the rejection, the user checks their balance again and sees:

`Last committed epoch: 61
No shielded balance found for given key`

P.S. I used Namada v0.32.1
P.S.S I used my own node with last version Namada v0.32.1

**Comment by grarco** [comment] 2024-03-27 21:09
Hi @monleru, could you give us the exact commands you used to reproduce this error?

**Comment by monleru** [comment] 2024-03-27 21:19
> Hi @monleru, could you give us the exact commands you used to reproduce this error?

Create new shielded alias 
Create shielded payment address
Transfer token to shielded payment address
Shielded-sync from 237907 
Check balance ( i see my tokens )
Send unshielded transfer and reject it
Check balance ( i don't see my tokens )

**Comment by monleru** [comment] 2024-03-27 21:27
1. namada wallet gen --shielded --alias test-test

2. namadaw gen-payment-addr \
    --key test-test \                
    --alias test-test-pay   
    
3. namadac  transfer --source monleru --target test-test-pay --amount 1 --token naan --node $NODE

4. namadac shielded-sync --node $NODE --from-height  237907
Scanning 397 of 397
[####################################################################################################] ~~ 100 %Syncing finished

5. namadac balance --owner test-test --node $NODE                            
Last committed epoch: 61
naan : 1

6. namadac balance --owner test-test --node $NODE                            
Last committed epoch: 61
naan : 1

7. namadac transfer  --source test-test --target monleru --amount 0.1 --token naan  --node  $NODE --memo  $MEMO  --gas-payer monleru

8. namadac balance --owner test-test --node $NODE                                                                              
Last committed epoch: 61
No shielded balance found for given key

**Comment by monleru** [comment] 2024-03-27 21:33
After resync (shielded-sync) i see my balance again but can't send transaction

**Comment by quangtuyen88** [comment] 2024-03-28 03:23
Can confirm got same err

**Comment by Zipporol** [comment] 2024-03-28 05:46
Same error

**Comment by phy-chain** [comment] 2024-03-28 09:39
To elaborate a bit more on that :
- Same issue here, with a NEW shielded address
- I have tried dropping the shielded.dat and re-syncing from HF start height, then normal sync => not working
- I have tried dropping my whole namada folder and joining network again to get the newest wasm, just in case => not working

**Comment by grarco** [comment] 2024-03-28 10:16
The issue regarding the missing tokens (unless resyncing) is most probably due to the first point of #2593. We are investigating the broken transfers

**Comment by grarco** [comment] 2024-03-28 14:20
Quick update, we investigated the problem which is due to the client producing merkle paths for the spend notes that point to invalid anchors (which in turn leads to a rejection by the masp vp). This is likely because the clients are not fetching all the notes published on chain and therefore construct invalid merkle trees locally. We are evaluating possible solutions

**Comment by opsecx** [comment] 2024-03-31 09:51
> Quick update, we investigated the problem which is due to the client producing merkle paths for the spend notes that point to invalid anchors (which in turn leads to a rejection by the masp vp). This is likely because the clients are not fetching all the notes published on chain and therefore construct invalid merkle trees locally. We are evaluating possible solutions

is that due to not being fully synced pre-fork?

**Comment by Zipporol** [comment] 2024-04-02 11:22
> Quick update, we investigated the problem which is due to the client producing merkle paths for the spend notes that point to invalid anchors (which in turn leads to a rejection by the masp vp). This is likely because the clients are not fetching all the notes published on chain and therefore construct invalid merkle trees locally. We are evaluating possible solutions

Hello! Can you inform us how things are going at the moment with the solution to the problem?

**Comment by Serge-GHSHCH** [comment] 2024-04-03 13:06
I have the same problem. Is there a forecast for the solution?

**Comment by brentstone** [comment] 2024-04-05 07:16
We are working on a solution for mainnet here, but a solution is not going to be expected for the SE so that we do not allocate valuable engineering time toward temporary fixes for the SE. Thanks for the discussion here, closing the issue now.

**Closed by brentstone** 2024-04-05 07:16 UTC
Labels: bug
